# Base configs
baseurl: "https://dariocast.github.io/artwork"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Artworks by Dario"
subtitle: "See the world through my eyes!"
author: "Dario Castellano"
header:
 title: "Artworks"
 subtitle: "by Dario"
footer:
 name: "Hey there, my name is Dario"
 bio: ""
web_design: "AJ"
#social_urls:
#  facebook: "https://www.facebook.com/ramswaroop"
#  twitter: "https://www.twitter.com/ram__patra"
#  instagram: "https://www.instagram.com/ram_patra"
#  dribbble: "https://dribbble.com/rampatra"
#  linkedin: "https://in.linkedin.com/in/ram-patra"
